"""数据集注册表 —— 全流水线的单一事实源。

每个数据集一条声明：构建器（module:function）、产物、来源/许可/署名、更新节奏、
时间轴归属（replay 回放轴 / history 历史轴 / snapshot 快照 / base 基底）。
run.py 据此做选择性构建、产物校验，并生成 public/data/manifest.json 供前端派生
文件清单、面板分组、署名页脚——**新增数据源只需：写一个构建函数 + 在此加一条注册**。
详见 docs/ADDING-A-DATASOURCE.md。
"""
from dataclasses import dataclass, field


@dataclass
class Dataset:
    id: str
    title: str                      # 面板/署名用中文名 · 来源简称
    builder: str                    # "module:function"
    outputs: list                   # public/data/ 相对路径
    stage: str                      # static | dynamic | series | heavy | adapter
    time_axis: str                  # replay | history | snapshot | base
    source: str                     # 来源主页/端点（人读）
    license: str
    attribution: str
    cadence: str = "manual"         # 预期更新节奏（说明性）
    synthetic: bool = False         # 合成/降级数据（前端标 SYNTHETIC）
    daily: bool = False             # 每日动态刷新（run.py --daily 名单 + 离线包成员）
    notes: str = ""


DATASETS = [
    # ---------- 基底 ----------
    Dataset("basemaps", "夜灯/地形基底 · NASA", "build_static:basemaps",
            ["nightlights.jpg", "bathymetry.jpg"], "static", "base",
            "NASA Black Marble / GIBS", "公开", "NASA Earth Observatory / GIBS",
            cadence="静态年版"),
    Dataset("zh_names", "资源数据汉化表 · 人工整编", "build_zh_names:main",
            ["zh_names.json"], "static", "base",
            "新华社/外交部译名习惯 + 台风委员会官方谱系（表内注记）", "事实数据（译名）",
            "Global Pulse curated",
            notes="国家全量断言/大港≥50 全覆盖断言；未收录回落原名"),
    Dataset("countries", "国界与质心 · Natural Earth", "build_static:countries",
            ["geometry/ne_50m.json", "geometry/centroids.json"], "static", "base",
            "naturalearthdata.com", "公有领域", "Natural Earth"),
    Dataset("ports", "港口 · Natural Earth", "build_static:ports",
            ["ports.json"], "static", "snapshot",
            "naturalearthdata.com", "公有领域", "Natural Earth"),
    # ---------- 基础设施（历史轴） ----------
    Dataset("cables", "海缆(RFS 年份) · TeleGeography", "build_static:cables",
            ["cables.json"], "static", "history",
            "submarinecablemap.com API v3", "CC BY-NC-SA 3.0（商用需授权）", "TeleGeography",
            cadence="随时重跑", notes="每缆详情端点含 rfs_year/is_planned"),
    Dataset("landing", "登陆站(最早接缆年) · TeleGeography", "build_landing_years:main",
            ["landing_points.json"], "static", "history",
            "submarinecablemap.com API v3", "CC BY-NC-SA 3.0", "TeleGeography",
            notes="依赖 cables 的缓存详情"),
    Dataset("pipelines", "油气管线(投运年) · GEM GGIT/GOIT", "build_pipelines_v2:main",
            ["pipelines.json"], "heavy", "history",
            "publicgemdata（GEM 公开数据桶）", "CC BY 4.0",
            "Global Gas/Oil Infrastructure Tracker, GEM",
            cadence="GGIT 2025-11 / GOIT 2026-06", notes="仅 operating；反子午线切割"),
    Dataset("power", "电厂机组(投运年) · GEM GIPT", "build_power_gipt:main",
            ["power_plants.json"], "heavy", "history",
            "publicgemdata（GEM 公开数据桶）", "CC BY 4.0",
            "Global Integrated Power Tracker, GEM, March 2026",
            cadence="2026-03 版", notes="12.7 万 operating 机组，光伏 8.1 万"),
    Dataset("transmission", "输电网 ≥220kV · OSM/OpenInfraMap", "build_transmission:main",
            ["transmission.json"], "heavy", "snapshot",
            "openinframap.org 矢量瓦片", "ODbL", "© OpenStreetMap contributors / OpenInfraMap",
            cadence="随时重跑"),
    # ---------- 历史长序列（历史轴） ----------
    Dataset("history", "长时段人口/CO₂ · HYDE/OWID", "build_history:main",
            ["pop_history.json", "co2_history.json"], "series", "history",
            "ourworldindata.org / owid co2-data", "CC BY", "OWID · HYDE · Global Carbon Project"),
    Dataset("indicators", "终章指标快照 · OWID(世行/SIPRI)", "build_indicators:main",
            ["finale/indicators.json", "finale/bivar_class_total.json",
             "finale/bivar_class_percap.json", "finale/milex.json",
             "finale/trade.json", "finale/gdp_pop.json"], "series", "snapshot",
            "ourworldindata.org grapher", "CC BY", "OWID / World Bank / SIPRI"),
    Dataset("indicator_series", "12 项指标全时序 · OWID", "build_indicator_series:main",
            ["finale/indicators_series.json"], "series", "history",
            "ourworldindata.org grapher", "CC BY", "OWID（世行/SIPRI/UN 等底层源）",
            notes="染色随年份回放；meta 含色标域"),
    Dataset("longrun_series", "20 项长时序指标 · OWID（公元1–）", "build_longrun_series:main",
            ["finale/longrun_series.json", "finale/attributions.json"], "series", "history",
            "ourworldindata.org grapher", "CC BY（V-Dem 底层 CC BY-SA）",
            "OWID（Maddison/V-Dem/WID/Gapminder/HFD/EI 等底层源）",
            cadence="底层源多为年更（metadata nextUpdate 可探测）", daily=True,
            notes="旁挂懒加载包；attributions.json=全部 grapher 指标署名+新鲜度"),
    Dataset("wb_series", "28 项治理/经济/基建/气候指标 · 世行直连", "build_worldbank:main",
            ["finale/wb_series.json"], "series", "history",
            "api.worldbank.org/v2（WDI source=2 / WGI source=3）", "CC BY 4.0",
            "World Development Indicators; Worldwide Governance Indicators 2025 Revision, "
            "World Bank (www.govindicators.org)",
            cadence="WDI 年 4 次 / WGI 年 1 次", daily=True,
            notes="首个直连世行构建器（本机间歇 502 带重试）；WGI 用 0-100 绝对分（SC）"),
    Dataset("sdg_series", "12 项 SDG 官方口径指标 · UN SDMX", "build_sdg:main",
            ["finale/sdg_series.json"], "series", "history",
            "data.un.org SDMX（DF_SDG_GLH）· unstats.un.org SDG Global Database",
            "UN Terms of Use（注明出处；商用需另行确认）",
            "United Nations Statistics Division, Global SDG Indicators Database",
            cadence="年 4 次大 release（3/6-7/9/12 月）", daily=True,
            notes="M49→ISO3 走 vendored 映射（pipeline/vendored/m49_iso3.json）；JMP 饮水/UNODC 凶杀官方口径"),
    Dataset("anomalies", "异常检测引擎 · 派生", "build_anomalies:main",
            ["finale/anomalies.json"], "series", "history",
            "本仓四序列包派生（indicators/longrun/sdg/wb 共 73 指标）",
            "派生产物（口径随各源包许可）", "Global Pulse derived",
            cadence="随四序列包重建", daily=True,
            notes="2.0 洞察层（DESIGN §2.1）：去趋势 z/单年跳变/序列极值三类，insight.js 消费；"
                  "共现≠因果口径入 meta.note；registry 序在四输入包之后（--daily 顺序执行依赖）"),
    Dataset("temp", "全球温度异常 1850– · HadCRUT/OWID", "build_temp:main",
            ["temp_stripes.json"], "series", "history",
            "ourworldindata.org grapher", "CC BY", "HadCRUT via OWID",
            cadence="上游月更，随每日刷新吸新（产物 2KB）", daily=True),
    Dataset("conflict", "冲突事件 · UCDP GED 26.1", "build_conflict:main",
            ["conflict_events.json", "finale/conflict_recent.json", "ged_history.json", "finale/camera_belt.json"],
            "series", "history",
            "ucdp.uu.se/downloads（免注册 zip）", "免费（官方引用格式）", "UCDP GED 26.1",
            cadence="年度基底+候选月度增量（每日刷新自动吸新月）", daily=True),
    Dataset("conflict_bin", "冲突全史列式 · GPB1 派生", "build_conflict_bin:main",
            ["conflict_events.bin"], "series", "history",
            "conflict_events.json 派生（(type,day) 排序 + tvSlices 切片头）",
            "同 conflict（UCDP 官方引用格式）", "UCDP GED via GPB1 columnar",
            cadence="随 conflict 重建", daily=True,
            notes="2.0 迁移弧（ARROW-PROBE §4）：体积 54%/内存 12×；registry 序在"
                  " conflict 之后（--daily 顺序依赖）；前端 binary attributes 直通"),
    Dataset("refugees", "难民流 · UNHCR", "build_flows:main",
            ["finale/refugee_flows.json"], "series", "snapshot",
            "api.unhcr.org", "开放", "UNHCR Refugee Population Statistics",
            cadence="年度（每年 6 月）"),
    Dataset("urban", "城市建成区 4 期 · GHSL UCDB", "build_urban:main",
            ["urban.json"], "static", "history",
            "JRC GHSL（直下 zip）", "CC BY 4.0", "GHSL UCDB R2019A, JRC"),
    Dataset("seaice", "海冰九月范围 1979– · NSIDC", "build_seaice:main",
            ["seaice.json"], "series", "history",
            "noaadata.apps.nsidc.org G02135", "公开", "NSIDC Sea Ice Index v4",
            cadence="年度（次年 10 月）"),
    Dataset("ntl", "夜灯历史 1992–2024 · 调和 DMSP+VIIRS", "build_ntl_history:main",
            ["ntl/index.json"], "heavy", "history",
            "figshare 9828827（Li et al.）", "CC BY 4.0",
            "Li et al. harmonized DMSP+VIIRS NTL",
            notes="9 采样年 PNG；两代互校准由源数据完成"),
    # ---------- 太空 ----------
    Dataset("space", "SATCAT/星链/发射 · CelesTrak+LL2", "build_space:main",
            ["satcat_history.json", "finale/sat_count.json", "starlink_tle.json",
             "launches.json"], "dynamic", "history",
            "celestrak.org / ll.thespacedevs.com", "公开", "CelesTrak · TheSpaceDevs",
            cadence="TLE 时效数天", daily=True,
            notes="celestrak gp.php 有限流，403 时降级 Walker"),
    # ---------- 动态/回放轴 ----------
    Dataset("quakes", "地震 · USGS", "build_dynamic:quakes",
            ["quakes.json"], "dynamic", "replay",
            "earthquake.usgs.gov feed", "公有领域", "USGS", cadence="7 天滚动", daily=True),
    Dataset("fires", "火点 24h · NASA FIRMS", "build_dynamic:fires",
            ["fires.json"], "dynamic", "snapshot",
            "firms.modaps.eosdis.nasa.gov 公开 CSV", "公开", "NASA FIRMS", cadence="24h 滚动", daily=True),
    Dataset("aurora", "极光 · NOAA SWPC", "build_dynamic:aurora",
            ["aurora.json"], "dynamic", "snapshot",
            "services.swpc.noaa.gov", "公有领域", "NOAA SWPC OVATION", cadence="实时快照", daily=True),
    Dataset("storms", "台风轨迹 · NOAA IBTrACS", "build_dynamic:storms",
            ["storms.json", "storms_daily.json"], "dynamic", "replay",
            "ncei.noaa.gov IBTrACS last3years", "公开", "NOAA IBTrACS v04r01", cadence="每日更新", daily=True),
    Dataset("lightning", "闪电(气候学热区) · 合成", "build_dynamic:lightning_synthetic",
            ["lightning_synth.json"], "dynamic", "replay",
            "NASA LIS/OTD 气候分布近似", "—", "synthetic（Blitzortung 需社区握手）",
            synthetic=True),
    Dataset("gpsjam_synth", "GPS 干扰(降级) · 合成", "build_dynamic:gps_interference_synthetic",
            ["gps_interference_synth.json"], "dynamic", "replay",
            "公开报道干扰区近似", "—", "synthetic（实测版见 gpsjam 数据集）",
            synthetic=True),
    Dataset("gpsjam", "GPS 干扰实测切片 · adsb.lol NIC", "collect_gpsjam:main",
            ["gpsjam_series.json"], "adapter", "replay",
            "api.adsb.lol（gpsjam.org 方法论）", "开放 API", "adsb.lol 社区 ADS-B",
            cadence="采集器随采随新", notes="长跑积累更多时间切片"),
    Dataset("aisstream", "船舶实况切片 · aisstream.io", "collect_aisstream:main",
            ["ais_live.json"], "adapter", "replay",
            "aisstream.io WebSocket（免费 key，pipeline/.env）", "开放（署名）", "aisstream.io",
            cadence="采集器 2×/日 cron", notes="0.5° 网格抽稀每格≤4；60 切片滚动"),
    Dataset("traffic", "AIS 合成航线+渔业+OpenSky 航班", "build_traffic:main_all",
            ["ais_synth.json", "fishing_synth.json", "flights_replay.json"],
            "dynamic", "replay",
            "NE 港口+真实航道路点 / opensky-network.org", "OpenSky 研究条款",
            "OpenSky Network；AIS/渔业 synthetic（aisstream/GFW 需 key）",
            cadence="航班快照每日重采（帧缓存 12h 过期）", daily=True,
            synthetic=True,
            notes="航线穿陆 QC=0；航班为真实快照回放。flights_replay.json 3.5MB/日"
                  "——云端不回推 git（防仓库膨胀），由动态包/逐日档案承载"),
    Dataset("shipdensity", "船舶密度 2015–21 · 世行 AIS", "build_shipdensity:main",
            ["ship_density_global.png", "ship_density_global.json"], "heavy", "snapshot",
            "datacatalog.worldbank.org（535MB zip，续传下载）", "CC BY 4.0",
            "World Bank Global Shipping Traffic Density"),
    # ---------- 旁白 ----------
    Dataset("narration", "解说字幕+配音 · edge-tts", "build_voiceover:main",
            ["narration.json"], "adapter", "base",
            "词表在 build_voiceover.py CUES", "—", "zh-CN-YunjianNeural TTS",
            notes="改词删对应 mp3 重跑"),
    # ---------- 需 key/手动的适配器 ----------
    Dataset("acled", "政治暴力/抗议 2020– · ACLED", "build_acled:main",
            ["acled.json"], "adapter", "replay",
            "ACLED 门户策展聚合包（raw/acled/，账号下载，禁再分发已 gitignore）",
            "非商业免费（商用需授权；原始文件不入库）", "ACLED",
            notes="事件级 API 未获批→策展聚合口径 admin1×月×类型；刷新=门户重下 zip 解包后重跑"),
    Dataset("resourcetrade", "资源贸易流 · Chatham House", "build_resourcetrade:main",
            ["resource_trade.json"], "adapter", "snapshot",
            "resourcetrade.earth（站内下载 xlsx）", "注明出处", "Chatham House RTD",
            notes="手动下载后导入"),
    Dataset("spaceweather", "空间天气 · NOAA SWPC", "build_spaceweather:main",
            ["spaceweather.json"], "dynamic", "snapshot",
            "services.swpc.noaa.gov", "公有领域", "NOAA SWPC", daily=True),
    Dataset("gdacs", "灾害告警 · GDACS(EU/JRC)", "build_gdacs:main",
            ["gdacs.json"], "dynamic", "snapshot",
            "gdacs.org（欧盟 JRC/UN OCHA）", "公开", "GDACS, EC-JRC", daily=True),
    Dataset("events", "异常年自动标注 · 派生", "build_events:main",
            ["events.json"], "series", "history",
            "本流水线时序统计（派生数据集）", "同各源", "Global Pulse derived",
            cadence="随每日刷新重算（消费各 daily 数据集，注册序在其后）", daily=True),
    Dataset("ucdp_violence", "组织性暴力死亡 国家-年 · UCDP", "build_ucdp_violence:main",
            ["finale/ucdp_violence.json"], "series", "history",
            "ucdpapi.pcr.uu.se organizedviolencecy（API 需 UCDP_TOKEN；免费申请）",
            "免费（官方引用格式）", "UCDP organizedviolencecy v26.1",
            cadence="年度版（候选口径不入此聚合集）",
            notes="官方国家-年聚合（sb+ns+os best 合计）；无 token 优雅跳过"),
    Dataset("blocs", "阵营版图 1945– · 条约整编", "build_blocs:main",
            ["blocs.json"], "series", "history",
            "条约文本与官方成员名单（北约/华约/里约/马尼拉/苏联友好条约——来源注于 build_blocs.py）",
            "事实数据（条约日期）", "Global Pulse curated",
            notes="人工整编，条约口径；东方阵营以 1991 封顶"),
    Dataset("colt", "领导人出访 1990–2023 · COLT", "build_colt:main",
            ["leader_visits.json"], "series", "history",
            "Harvard Dataverse doi:10.7910/DVN/87YG4K（Pardee Diplometrics，ISQ 2025）",
            "CC0 1.0", "Moyer et al., When HOGS Fly (ISQ 2025)",
            notes="leader-trip 级聚合为国家对-年；IGO 领导人剔除；历史国家质心近似映射"),
    Dataset("g2visits", "中美元首外交 2013– · visit-g2", "build_visitg2:main",
            ["g2_visits.json"], "series", "history",
            "~/work/visit-g2 自建库（口径对齐 ASPI Thomas & Wei 2026）",
            "自建汇编（US State Dept 公有领域 + MFA/Wayback 事实提取 + Wikipedia CC BY-SA）",
            "visit-g2（自建）· ASPI 口径",
            notes="手动阶段：源库 run_monthly.sh 后重跑本构建器；Actions 无源库不入 --daily"),
    Dataset("sanctions", "制裁行动 2025– · OFAC", "build_sanctions:main",
            ["sanction_events.json"], "series", "history",
            "sanctionslistservice.ofac.treas.gov/changes（官方 Delta 通道）",
            "公有领域（美国联邦政府作品，17 U.S.C. §105）",
            "U.S. Treasury OFAC — Sanctions List Service",
            cadence="每工作日（逐 publication immutable 缓存）", daily=True,
            notes="2.0 §1.1 首切片：国家-日事件聚合，不含实体名单；target_iso=计划映射"
                  "优先/主题类回落地址国（口径入 meta.note）；扩年只需 YEARS 加项"),
    Dataset("covid", "疫情 COVID · OWID", "build_covid:main",
            ["covid.json", "finale/covid_series.json"], "series", "history",
            "catalog.ourworldindata.org compact.csv（178MB，immutable 缓存）",
            "CC BY 4.0（OWID；上游 WHO/JHU 事实数据）",
            "Our World in Data — COVID-19 dataset",
            cadence="手动年度刷新（源 WHO 通道低频续更；删缓存重跑）",
            notes="2.0 §1.5 切片第二号：周格层数据 + 年度旁挂包；covid_deaths_pm"
                  " 5 点序列不进异常引擎（MIN_POINTS=10，z 无意义——诚实原则）"),
    Dataset("flunet", "流感阳性率 2018– · WHO FluNet", "build_flunet:main",
            ["finale/flunet_weekly.json"], "series", "history",
            "xmart-api-public.who.int/FLUMART/VIW_FNT（OData，免登录，$select 减载分页）",
            "CC BY-NC-SA 3.0 IGO（非商业 + 衍生同许可；非 ND 故允许改编——"
            "与 EM-DAT NC-ND 拒接先例的分界）",
            "World Health Organization — FluNet (GISRS)",
            cadence="周更（WHO 每周发布；缓存按页，扩窗改 YEAR_FROM）",
            notes="传染病切片第一号：阳性率=ΣINF_ALL/ΣSPEC_PROCESSED_NB（同国同周跨"
                  "SENTINEL/NONSENTINEL 流先求和再相除）；分母<20 置空；"
                  "**零阳性周救回**（INF_ALL 空且 INF_NEGATIVE==分母 → 记 0，"
                  "否则淡季被整段弃行、阳性率系统性抬高）；英国四构成国 X09-X12 并入 GBR；"
                  "半球表实测仅 NH/SH 两值（无 TR 档）；报告偏倚硬注记入 meta.bias"),
    Dataset("gho", "霍乱/结核年度 · WHO GHO", "build_gho:main",
            ["finale/gho_series.json"], "series", "history",
            "ghoapi.azureedge.net/api/{IndicatorCode}（OData，免登录）",
            "CC BY-NC-SA 3.0 IGO（非商业 + 衍生同许可）",
            "World Health Organization — Global Health Observatory",
            cadence="年度手动（霍乱上游已冻结于 2016；结核随 WHO 年报更新）",
            notes="传染病切片补充：cholera_cases/cholera_deaths/tb_incidence 三序列"
                  "旁挂包（{meta,series} 同构，复用既有 prep 通道）；结核码坑=全型发病率"
                  "在 MDG_0000000020，搜索首中的 TB_e_inc_tbhiv_100k 仅 HIV 阳性子集；"
                  "取值双通道（霍乱 NumericValue 多空→解析 Value；结核 Value 带区间"
                  "→取 NumericValue）；单指标失败不阻塞其余"),
    Dataset("chokepoints", "海运咽喉点 2019– · IMF PortWatch", "build_portwatch:main",
            ["chokepoints.json"], "series", "history",
            "portwatch.imf.org（ArcGIS FeatureServer/Hub CSV，每周二更新）",
            "IMF Data 条款：可再分发含商用，须署名（terms.htm 2026-07 已核原文）",
            "Source: International Monetary Fund — PortWatch",
            cadence="每周二（缓存 2 天 TTL）", daily=True,
            notes="2.0 §2.3 切片第三号：28 咽喉点过境船次 7 日均 + 全期中位基线；"
                  "红海危机锚点：曼德海峡 2023-11=73.9→2024-02=31.6"),
    Dataset("idmc", "境内流离失所 2008– · IDMC GIDD", "build_idmc:main",
            ["finale/idmc_series.json"], "series", "history",
            "HDX（IDMC 官方组织页，xlsx）", "CC BY 4.0（HDX license 已核）",
            "Internal Displacement Monitoring Centre (IDMC), GIDD",
            cadence="年度（GRID 每年 5 月；缓存 30 天）",
            notes="2.0 §1.6 切片第四号：disp_disaster/disp_conflict 双序列旁挂包，"
                  "≥10 点过异常引擎门槛（PAK 2010 洪水极值/UKR 2022 冲突极值锚点）"),
    Dataset("storms_history", "台风全史 1980– · IBTrACS", "build_storms_history:main",
            ["storms_history.json"], "series", "history",
            "ncei.noaa.gov IBTrACS since1980（143MB immutable 缓存）", "公开（NOAA）",
            "NOAA IBTrACS v04r01",
            cadence="年度手动刷新（删缓存重跑吸新季）",
            notes="2.0 §1.6 切片第四号：有名风暴逐 12h 抽稀轨迹，历史轴逐年回放；"
                  "海燕 2013/卡特里娜 2005 锚点"),
    Dataset("calls", "元首通话 2021– · 白宫 readouts", "build_calls:main",
            ["calls.json"], "series", "history",
            "白宫 briefing room（拜登期 Wayback CDX slug 枚举 + 现任 post-sitemap）",
            "公有领域（美国联邦政府作品，17 U.S.C. §105）",
            "The White House — presidential call readouts",
            cadence="月度手动（现任发布稀少系风格变化；中方通道留 visit-g2 方法链回填）",
            notes="2.0 §1.2 切片第五号：总统级通话事件 [day,iso,k]，k=1 美方；"
                  "锚点=拜登-习近平全部 5 次通话逐一在数据"),
    Dataset("adm1", "省级钻取试点 · geoBoundaries×DOSE", "build_adm1:main",
            ["adm1/index.json", "adm1/BRA.json", "adm1/CHN.json", "adm1/DEU.json",
             "adm1/IND.json", "adm1/USA.json"], "static", "history",
            "geoboundaries.org gbOpen ADM1 + Zenodo 20035157 DOSE V2.14",
            "CC BY 4.0 ×2（Runfola et al. 2020；Wenz et al.——GADM 禁再分发故弃）",
            "geoBoundaries (Runfola et al.) · DOSE (Wenz et al.)",
            cadence="年度手动（DOSE 年版）",
            notes="2.0 §2.1/2.4 切片第六号：试点五国省级人均 GRP 年序列钻取；"
                  "匹配率 CHN31/34 USA51/56 IND30/36 BRA27/27 DEU16/16"),
    Dataset("conjunctions", "在轨交会告警 · SOCRATES", "build_conjunctions:main",
            ["conjunctions.json"], "dynamic", "snapshot",
            "celestrak.org/SOCRATES", "公开", "CelesTrak SOCRATES", daily=True),
    Dataset("radar", "互联网态势 · Cloudflare Radar", "build_radar:main",
            ["radar.json"], "dynamic", "snapshot",
            "api.cloudflare.com/radar（需免费 token）", "公开（署名 Cloudflare Radar）", "Cloudflare Radar", daily=True),
    Dataset("carbon", "电网碳强度实时 · Electricity Maps", "build_carbon:main",
            ["carbon.json"], "dynamic", "snapshot",
            "api.electricitymap.org（需免费 token）", "公开（署名）", "Electricity Maps", daily=True),
    Dataset("daily_series", "逐日档案合成 · 派生", "build_daily_series:main",
            ["daily_series.json"], "series", "history",
            "本流水线当日产物压缩累积（历史长轴末端日粒度）", "同各源", "Global Pulse derived",
            cadence="每日追加（注册序在全部 daily 源之后）", daily=True,
            notes="qk 按发生日归属其余按采集日；--backfill 可回填 dist 历史包"),
    Dataset("finance_layers", "全球金融流层 1977– · finance-layer", "build_finance_layers:main",
            ["finance_nodes.json", "finance_arcs.json", "finance_events.json",
             "finance_wells.json"], "adapter", "history",
            "finance-layer/ 子仓 build/ 产物（IMF CDIS/BIS LBS/US TIC/CEPII BACI/"
            "yfinance/CoinMetrics/World Gold Council）",
            "各源原许可（IMF/BIS/TIC 公开统计；BACI 学术使用；yfinance 非商用）",
            "IMF CDIS · BIS Locational Banking Statistics · US Treasury TIC · CEPII BACI · "
            "yfinance · CoinMetrics · World Gold Council",
            cadence="随 finance-layer 重跑（年度源为主）",
            notes="选项 2 裁定：金融层进交互探索台与冲突/难民/夜灯跨层叠看；"
                  "同源不同用——出片资产留在 finance-layer/scene_assets 独立管线。"
                  "每类每年 top-40 弧、events 仅 approved 包；四文件 <3MB 体积红线，"
                  "契约校验见 scripts/finance-data-probe.mjs"),
    Dataset("worldpop_adm1", "省级人口 · WorldPop 1km UNadj 2020", "build_worldpop_adm1:main",
            ["adm1/index.json"], "series", "adm1",
            "data.worldpop.org 1km UNadj 栅格 × adm1 分区统计", "CC BY 4.0",
            "WorldPop（Bondarenko et al. 2020）",
            notes="手动节奏：随 adm1 名单或 WorldPop 年版更新重跑；552MB 栅格缓存不入库"),
]

BY_ID = {d.id: d for d in DATASETS}
